### ISSUE TITLE
Tips on usage

### ISSUE THREAD

**Issue by darleybarreto** [programmerjake/simple-soft-float#1]
First of all great work on this implementation! I have a couple of questions about this crate and I would appreciate so much if you could take a bit of your time to look into them. 

- Is there any significant difference in the Rust backend between master and the version on crates.io?

- Is the version on crates.io ready to use in some "serious" applications? Let's say to interface with ffi C long double?

- Do you have any small example of rust code using the crate as a drop-in replacement of a type?

- How would I convert ffi C long double to a 80 (or 128, I'm not sure which) bits representation?

Thanks in advance!

**Comment by programmerjake** [comment]
> First of all great work on this implementation! I have a couple of questions about this crate and I would appreciate so much if you could take a bit of your time to look into them.
> 
> * Is there any significant difference in the Rust backend between master and the version on crates.io?

Yes, the API changed for `StatusFlags` (and will change more as part of adding all of PowerPC's custom status flags) and I switched the version of PyO3 used to support compiling on Rust stable.

> * Is the version on crates.io ready to use in some "serious" applications? Let's say to interface with ffi C long double?

There's two issues with FFI:
1. actually supporting the types and operations -- simple-soft-float can do this with some caveats:
    * simple-soft-float doesn't have an implementation for x86 80-bit floats since those are quite unusual
    * for platforms other than RISC-V, simple-soft-float don't always produce the correct NaN payload. This means it may produce a different NaN than the expected one, but it is still a NaN.
    * simple-soft-float is designed for testing CPU hardware to make sure they produce the correct results, so is not optimized for speed.
    * simple-soft-float doesn't have a particularly ergonomic API
2. supporting all the CPU registers & special calling protocols that are used for passing values to/returning values from functions (e.g. using the x87 FPU stack on x86-32) -- simple-soft-float can't do this by itself and isn't intended to, since special compiler support is necessary to generate the right instructions.

> * Do you have any small example of rust code using the crate as a drop-in replacement of a type?

Not really, sorry.

> * How would I convert ffi C long double to a 80 (or 128, I'm not sure which) bits representation?

If you want a 128-bit float for RISC-V, you could use:
```rust
pub unsafe fn read_ffi_long_double(p: *const c_void) -> F128 {
    let bits: u128 = std::ptr::read_unaligned(p as *const u128); // long double may have different alignment to u128
    F128::from_bits(bits)
}

pub unsafe fn write_ffi_long_double(p: *mut c_void. v: F128) {
    let bits: u128 = v.into_bits();
    std::ptr::write_unaligned(p as *mut u128, bits); // long double may have different alignment to u128
}

#[no_mangle]
pub unsafe extern "C" fn my_fn(dest: *mut c_void, src: *const c_void) {
    let v = read_ffi_long_double(src);
    let three = F128::from_i32(3, None, None);
    v = v.add(&three, None, None);
    write_ffi_long_double(dest, v);
}
```

Then you could call `my_fn` from C++ like so:
```C++
#include <iostream>
#include <limits>
void my_fn(void *dest, const void *src);

int main() {
    long double v1, v2;
    static_assert(sizeof(long double) == 16, "long double isn't a 128-bit float");
    static_assert(std::numeric_limits<long double>::digits == 113, "long double isn't a 128-bit float");
    v2 = 1.25;
    my_fn((void *)&v1, (const void *)&v2);
    std::cout << v1 << std::endl; // prints 4.25
    return 0;
}
```

128-bit floats for other platforms require you to use a different type since RISC-V is the default platform:
```rust
#[derive(Copy, Clone, Hash, Eq, PartialEq, Debug, Default)]
pub struct F128SPARCTraits;

impl FloatTraits for F128SPARCTraits {
    type Bits = u128;
    fn properties(&self) -> FloatProperties {
        FloatProperties::standard_128_with_platform_properties(PlatformProperties::SPARC)
    }
}

type F128SPARC = Float<F128SPARCTraits>;

pub unsafe fn read_ffi_long_double(p: *const c_void) -> F128SPARC {
    let bits: u128 = std::ptr::read_unaligned(p as *const u128); // long double may have different alignment to u128
    F128SPARC::from_bits(bits)
}

pub unsafe fn write_ffi_long_double(p: *mut c_void. v: F128SPARC) {
    let bits: u128 = v.into_bits();
    std::ptr::write_unaligned(p as *mut u128, bits); // long double may have different alignment to u128
}
```
> 
> Thanks in advance!

Hopefully that was helpful!

**Comment by darleybarreto** [comment]
Thank you so much for you time and great response, it certainly helped me out!
